// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository;

#nullable disable

namespace CSharpTest.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220811003442_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Entities.Request", b =>
                {
                    b.Property<long>("Rid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Rid"), 1L, 1);

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("char(1)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Rid");

                    b.ToTable("Request");
                });

            modelBuilder.Entity("Entities.SearchRequest", b =>
                {
                    b.Property<long>("Rid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Rid"), 1L, 1);

                    b.Property<int?>("Hits")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Search")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("SuccessInd")
                        .IsRequired()
                        .HasColumnType("char(1)");

                    b.HasKey("Rid");

                    b.ToTable("SearchRequest");
                });

            modelBuilder.Entity("Entities.SearchTopProducts", b =>
                {
                    b.Property<long?>("Rid")
                        .HasColumnType("bigint")
                        .HasColumnOrder(0);

                    b.Property<int?>("Order")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Rid", "Order");

                    b.ToTable("SearchTopProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
